packages:
  - packages/*

catalog:
  '@livestore/adapter-node': 0.4.0-dev.8
  '@livestore/adapter-web': 0.4.0-dev.8
  '@livestore/devtools-vite': 0.4.0-dev.8
  '@livestore/livestore': 0.4.0-dev.8
  '@livestore/peer-deps': 0.4.0-dev.8
  '@livestore/react': 0.4.0-dev.8
  '@livestore/sync-cf': 0.4.0-dev.8
  '@livestore/utils': 0.4.0-dev.8
  '@livestore/wa-sqlite': 0.4.0-dev.8
  effect: ^3.17.13
  typescript: ^5.8.3
  '@types/node': ^24.1.0
  tsx: ^4.20.3
  vitest: ^3.2.4
  eslint: ^9.32.0
  prettier: ^3.6.2
  '@typescript-eslint/eslint-plugin': ^8.38.0
  '@typescript-eslint/parser': ^8.38.0
  vite: ^7.1.3
  wrangler: 4.38.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - workerd
