packages:
  - packages/*

catalog:
  "@livestore/adapter-node": 0.4.0-dev.7
  "@livestore/adapter-web": 0.4.0-dev.7
  "@livestore/devtools-vite": 0.4.0-dev.7
  "@livestore/livestore": 0.4.0-dev.7
  "@livestore/peer-deps": 0.4.0-dev.7
  "@livestore/react": 0.4.0-dev.7
  "@livestore/sync-cf": 0.4.0-dev.7
  "@livestore/utils": 0.4.0-dev.7
  "@livestore/wa-sqlite": 0.4.0-dev.7

  # Effect packages (required by LiveStore)
  "effect": "^3.17.13"
  "@effect/platform": "^0.90.10"
  "@effect/schema": "^0.91.10"
  "@effect/rpc": "^0.69.3"
  "@effect/cluster": "^0.48.10"
  "@effect/sql": "^0.44.2"

  # Common dev dependencies
  typescript: "^5.8.3"
  "@types/node": "^24.1.0"
  tsx: "^4.20.3"
  vitest: "^3.2.4"
  eslint: "^9.32.0"
  prettier: "^3.6.2"
  "@typescript-eslint/eslint-plugin": "^8.38.0"
  "@typescript-eslint/parser": "^8.38.0"
  vite: "^7.1.3"
  wrangler: "^4.26.1"

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - workerd
