packages:
  - packages/*

catalog:
  "@livestore/adapter-node": 0.3.1
  "@livestore/adapter-web": 0.3.1
  "@livestore/devtools-vite": 0.3.1
  "@livestore/livestore": 0.3.1
  "@livestore/peer-deps": 0.3.1
  "@livestore/react": 0.3.1
  "@livestore/sync-cf": 0.3.1
  "@livestore/utils": 0.3.1
  "@livestore/wa-sqlite": 1.0.5

  # Common dev dependencies
  typescript: "^5.8.3"
  "@types/node": "^24.1.0"
  tsx: "^4.20.3"
  vitest: "^3.2.4"
  eslint: "^9.32.0"
  prettier: "^3.6.2"
  "@typescript-eslint/eslint-plugin": "^8.38.0"
  "@typescript-eslint/parser": "^8.38.0"
  vite: "^7.0.6"
  wrangler: "^4.26.1"

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - workerd
